### ISSUE TITLE
isort error due to isort v5

### ISSUE THREAD

**Issue by maresb** [dmontagu/fastapi_client#13]
I am getting
```
isort: error: argument -a/--add-import: expected one argument
```
This is apparently due to isort v5 being installed in the Dockerfile. If I edit the `pip` command in the Dockerfile to pin `isort==4.3.21` it works again.

Sorry I don't have time right now to analyze it in more depth, but I wanted to at least report it.

**Comment by dmontagu** [comment]
Should be fixed
