### ISSUE TITLE
Full Python: no Bash, no Docker

### ISSUE THREAD

**Issue by pawamoy** [dmontagu/fastapi_client#15]
Would you consider refactoring this project as a Python CLI tool?

Currently I cannot even try it, because I need to clone the repository to be able to run the Bash scripts, and my corporate proxy is sensitive (if often rejects git clones), and the scripts try to pull a Docker image from community repositories which are blocked by my corporate proxy.

Looking at the Dockerfile, it seems that it would be fairly simple to configure the project as a Python package with these dependencies; `black autoflake isort httpx fastapi typing_extensions`. Then the Bash scripts would be rewritten in Python (could be more complicated, I just glanced at them). Users could then install the project with `pipx`, and run it like `fastapi-client OPTS...`. This is the approach [`openapi-python-client`](https://github.com/triaxtec/openapi-python-client) is taking for example :slightly_smiling_face:

**Comment by dmontagu** [comment]
Very much open to it if someone wants to put in the effort!

**Comment by pawamoy** [comment]
I don't think this project is active anymore, so I'll close this. Feel free to reopen :slightly_smiling_face:
