### ISSUE TITLE
adding License  notice

### ISSUE THREAD

**Issue by ChristopheLallement** [dmontagu/fastapi_client#20]
Hello

I  open this ticket to propose a Pull-request concerning the licenses.
We would like to use your project as part of an open-source project and we  must  comply with  license law.
There are two aspects  the license of fastapi_client code and  the license of the generated code.

1. License of the project
For the moment since  there is no license  the default copy  copyright law applies, no one may reproduce, distribute, or create derivative works.  [source GitHub documentation](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository)

2. License of the generated code
Since the project doesn't have any license yet, the default copyrights apply to the template. By consequence  the generated code include some copyrighted code.  **In my understanding  nobody can use eventually the generated code.**

For these reasons, could you consider adding :
- A license in the project 
- A notice about the generated code  licence.

I could  take charge of  the modification and  the Pull-request.
Will you accept a pull request to do same as openapi-generator did regarding the license ? 

Openapi-generator is under apache 2.0 license and the project  contains the following notice :

> 3.4 - License information on Generated Code
The OpenAPI Generator project is intended as a benefit for users of the Open API Specification. The project itself has the License as specified. In addition, please understand the following points:
>
>The templates included with this project are subject to the License.
>Generated code is intentionally not subject to the parent project license
>When code is generated from this project, it shall be considered AS IS and owned by the user of the software. There are no warranties--expressed or implied--for generated code. You can do what you wish with it, and once generated, the code is your responsibility and subject to the licensing terms that you deem appropriate.
>[source](https://github.com/OpenAPITools/openapi-generator/blob/master/README.md#34---license-information-on-generated-code)

Thanks
Christophe

**Comment by dmontagu** [comment]
Sorry for the delay!

**Comment by ChristopheLallement** [comment]
Thanks you David
