### ISSUE TITLE
Client dependencies issues

### ISSUE THREAD

**Issue by fj-sanchez** [dmontagu/fastapi_client#8]
Hi, I discovered this today when I was about to try something similar. I've run the project in my machine but I get import errors which I suspect is due to different versions in the dependencies (httpx, fastapi, etc.). I have tried to install using poetry but it refuses to install and also the lock seems to be outdated (I can run `poetry lock` and then `poetry install` and it installs everything correctly).

The error that I get when importing is this:

```
~/.pyenv/versions/3.7.5/envs/fastapi_client/lib/python3.7/site-packages/pydantic/main.cpython-37m-x86_64-linux-gnu.so in pydantic.main.MetaModel.__new__()

~/.pyenv/versions/3.7.5/envs/fastapi_client/lib/python3.7/site-packages/pydantic/utils.cpython-37m-x86_64-linux-gnu.so in pydantic.utils.resolve_annotations()

~/.pyenv/versions/3.7.5/lib/python3.7/typing.py in _eval_type(t, globalns, localns)
    261     """
    262     if isinstance(t, ForwardRef):
--> 263         return t._evaluate(globalns, localns)
    264     if isinstance(t, _GenericAlias):
    265         ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)

~/.pyenv/versions/3.7.5/lib/python3.7/typing.py in _evaluate(self, globalns, localns)
    465                 localns = globalns
    466             self.__forward_value__ = _type_check(
--> 467                 eval(self.__forward_code__, globalns, localns),
    468                 "Forward references must evaluate to types.",
    469                 is_argument=self.__forward_is_argument__)

~/src/fastapi_client/generated/hubble_client/models.py in <module>

TypeError: dict expected at most 1 arguments, got 2
```

This happens when trying to evaluate this generated pydantic model:

```
class ArtifactInDBBase(BaseModel):
    name: "str" = Schema(..., alias="name")  # type: ignore
    type: "str" = Schema(..., alias="type")  # type: ignore
    data_objectkey: "str" = Schema(..., alias="data_objectkey")  # type: ignore
```
As you can see it has one attribute called `type`, could this be the cause of the issue?

UPDATE: I have tried to rename the attribute to `type_` but still the same error.

**Comment by dmontagu** [comment]
Yeah it has a number of old dependencies now I’m happy to update. Any chance you can make a small reproducible example that you can share? If so I’m happy to debug it.

**Comment by fj-sanchez** [comment]
I've managed to fix the issues, one of them I think was related to user permissions after running the Docker images. I think it would be better to specify the user that runs the container (i.e. add `--user $(id -u):$(id -g)` to the arguments of each docker run). Another issue is that when building the pydantic models, it converts `Dict[X,X]` into `dict(x,x)`, which doesn't seem to be accepted as `dict` only expects one argument, not two. I've manually corrected it but I yet have to check to fix it properly.

One issue that I have right now is this error when calling one of the generated requests:
```
~/.cache/pypoetry/virtualenvs/example-hBNawbCz-py3.7/lib/python3.7/site-packages/pydantic/main.cpython-37m-x86_64-linux-gnu.so in pydantic.main.validate_model()

ConfigError: field "summary" not yet prepared so type is still a ForwardRef, you might need to call ExecutionSuite.update_forward_refs().
```
If I do as the error suggests and run `ExecutionSuite.update_forward_refs()`  then everything works fine in the next call of the same method. Is there any way to get rid of this?

**Comment by dmontagu** [comment]
Yeah some of these challenges are related to awkwardness between how openapi-generator works and how python works. In particular, in python (and especially with pydantic), you have to be careful about import and definition ordering. This is in contrast with Java and many of the other languages supported by openapi generator, so it isn't very surprising this doesn't work super well out of the box.

For that reason, I generally recommend sharing pydantic model code between your client and server (if you wrote the server and it is using pydantic models, anyway). So far I haven't found a great way to reliably generate a models package that will work for arbitrary OpenAPI specs, though PRs would be welcome to improve this.

For the specific problem of calling `update_forward_refs`, would it be enough to just dump an `update_forward_refs` call at the bottom of `__init__.py`?

------

Are you using pydantic v1? The included templates were designed for use with pydantic 0.x, and I think should be updated to use v1. But I am happy to hold off on that if it is going to break things for you. (At least I could put it behind some sort of flag.)

**Comment by fj-sanchez** [comment]
Yes, I have updated the libraries and swapped `Schema` by `Field`. Also I
have updated httpx and updated the various outdated Async/Sync responses,
etc. Also I've added from futures annotations so it can handle deferred
annotations.

I'll try tomorrow to fix the problem with the call to the update forward
ref method, it has to be called for every class AFAIK.

**Comment by fj-sanchez** [comment]
Ok, I've fixed the issue by following your suggestion:

`__init__package.mustache`
```
import inspect

import @IMPORT_NAME@.models  # noqa F401
from @IMPORT_NAME@.api_client import ApiClient, AsyncApis, SyncApis  # noqa F401


for model in inspect.getmembers(@IMPORT_NAME@.models, inspect.isclass):
	if model[1].__module__ == "@IMPORT_NAME@.models":
		model_class = model[1]
		model_class.update_forward_refs()
```
